version: "3"
services:
  controller:
    image: power_bi
    container_name: SPIbot
    restart: always
    working_dir: /app/main_api/SPI_Group
    command: ["python3", "task.py"]
    volumes:
      - /root/SPI_bot/Automation/Bot_program/Config_file:/app/main_api/SPI_Group/Config_file

  sql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "spi_group_windmill_data"
      MYSQL_USER: "RAP@Admin"
      MYSQL_PASSWORD: "RAPbOT@!@#"
      MYSQL_ROOT_PASSWORD: "RAPbOT@root!@#"
    ports:
      - "6024:3306"
    expose:
      - 6024
    container_name: SPImysql
    volumes:
      - /root/SPI_bot/db:/data/db/
