version: "3"
services:
  controller:
    image: power_bi
    container_name: bot
    restart: always
    working_dir: /app/main_api/SPI_Group
    command: ["python3", "task.py"]
    volumes:
      - /root/Jai/Automation/SPI_Group/OLD/Bot_program/Config_file:/app/main_api/SPI_Group/Config_file

  sql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "spi_group_replica"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "6603:3306"
    expose:
      - 6603
    container_name: sql
    volumes:
      - /root/Jai/db:/data/db/
